### PR TITLE
Fix bug plugin count in search results

### LINKED ISSUE #246: Search results bug
Searching for a plugin which does not exist shows "-1 plugins found"

https://next.chrisstore.co/plugins?q=doesnotexist

screenshot

### PR DESCRIPTION
**Pull request by EUGINELETHAL**
@zrthxn fixes #246

### CODE REVIEW

File: src/components/Plugins/Plugins.jsx [hunk 1]
```diff
@@ -325,58 +325,66 @@ export class Plugins extends Component {
...
       </div>
     )
 
+    let pluginsCount;
+
+    if (plugins.totalCount > 0) {
+      pluginsCount = plugins.totalCount;
+    } else {
+      pluginsCount = 0;
+    }
```
Comment (zrthxn) [inline src/components/Plugins/Plugins.jsx:377]: Just for kicks, can you condense this into a single line?

**Review by zrthxn — CHANGES_REQUESTED** [review]

**Comment by EUGINELETHAL** [comment]
yah let me condense into two
lines

File: src/components/Plugins/Plugins.jsx (hunk 1 above)
Comment (EUGINELETHAL) [reply src/components/Plugins/Plugins.jsx]: @zrthxn i have refactored the code into a single statement,thanks for feedback

**Review by zrthxn — APPROVED** [review]
