### PR TITLE
Replace sample data with data from the ChRIS store API

### LINKED ISSUE #3: Replace sample data with data from the ChRIS store API

### LINKED ISSUE #5: Fix broken navbar at 780px width

### PR DESCRIPTION
**Pull request by jdtzmn**
Closes #3 and fixes #5

### CODE REVIEW

**Comment by danmcp** [comment]
@jcaianirh Please review

File: src/components/Navbar/components/Search/Search.js [hunk 1]
```diff
@@ -0,0 +1,60 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import { Icon } from 'patternfly-react';
+import './Search.css';
+
+// a helper function to get query params from page url
+const getQueryParams = (search) => {
+  const groups = search.slice(1).split('&');
```
Comment (jcaianirh) [inline src/components/Navbar/components/Search/Search.js]: I would suggest starting to use lodash for any manipulation of arrays, strings, or objects. [lodash](https://lodash.com/docs/4.17.10)

File: src/components/Plugins/Plugins.js [hunk 2]
```diff
@@ -65,11 +83,11 @@ class Plugins extends Component {
     if (pluginListExists) {
```
Comment (jcaianirh) [inline src/components/Plugins/Plugins.js]: const { pluginList, categories } = this.state;
then just access pluginList || categories.

File: src/components/Plugins/Plugins.js [hunk 3]
```diff
@@ -1,9 +1,8 @@
 import React, { Component } from 'react';
+import { StoreClient } from '@fnndsc/chrisstoreapi';
 import { DropdownButton, MenuItem } from 'react-bootstrap';
 import PluginItem from './components/PluginItem/PluginItem';
 import PluginsCategories from './components/PluginsCategories/PluginsCategories';
-import formatPluginList from './formatPluginList';
-import sampleData from './samplePluginsData';
 import './Plugins.css';
 
 // ==============================
```
Comment (jcaianirh) [inline src/components/Plugins/Plugins.js]: no need to pass props to super if you're not using it here.

**Comment by jdtzmn** [comment]
@jcaianirh Updated Plugins.js

File: src/components/Plugins/Plugins.js [hunk 4]
```diff
@@ -72,16 +72,15 @@ class Plugins extends Component {
...
+    const { pluginList, categories } = this.state;
     let pluginListBody;
 
     // Remove email from author
     const removeEmail = author => author.replace(/( ?\(.*\))/g, '');
 
     // Render the pluginList if the plugins have been fetched
-    if (pluginListExists) {
-      pluginListBody = this.state.pluginList.map(plugin => (
+    if (pluginList) {
```
Comment (jcaianirh) [inline src/components/Plugins/Plugins.js]: you could always instantiate the length as 0 and change it when in this conditional since you've already checking pluginList once. not a strong opinion on this. yours is at least a single line :)

**Comment by jdtzmn** [comment]
Waiting on FNNDSC/fnndsc#20

**Comment by jdtzmn** [comment]
@jcaianirh One last review (and approve), and then I'll squash the commits and merge.
